name: CI

on:
  pull_request_target:
    types:
      - synchronize
      - opened
      - reopened

  workflow_dispatch:

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "npm"
      - name: test basic
        run: |
          npm ci
          npm run test:basic
  advacned:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "npm"
      - name: advanced-test
        run: |
          npm ci
          npm run test:advanced
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "npm"
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps
          npm run test:e2e
