name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 push할 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # 또는 프로젝트에서 사용하는 Node.js 버전

      - name: Install dependencies
        run: npm install # 또는 yarn install

      - name: Build
        run: npm run build # 또는 yarn build
        env:
          BASE_URL: "/${{ github.event.repository.name }}" # GitHub Pages URL에 맞게 base 설정

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Vite의 기본 빌드 출력 디렉토리
